In [1]:
note_seq = ['g8', 'e8', 'e4', 'f8', 'd8', 'd4', 'c8', 'd8', 'e8', 'f8', 'g8', 'g8', 'g4',
       'g8', 'e8', 'e8', 'e8', 'f8', 'd8', 'd4', 'c8', 'e8', 'g8', 'g8', 'e8', 'e8', 'e4',
       'd8', 'd8', 'd8', 'd8', 'd8', 'e8', 'f4', 'e8', 'e8', 'e8', 'e8', 'e8', 'f8', 'g4',
       'g8', 'e8', 'e4', 'f8', 'd8', 'd4', 'c8', 'e8', 'g8', 'g8', 'e8', 'e8', 'e4']

In [2]:
note_seq[0:4], note_seq[1:5], note_seq[2:6]

(['g8', 'e8', 'e4', 'f8'], ['e8', 'e4', 'f8', 'd8'], ['e4', 'f8', 'd8', 'd4'])

In [3]:
code2idx = {'c4':0, 'd4':1, 'e4':2, 'f4':3, 'g4':4, 'a4':5, 'b4':6,
            'c8':7, 'd8':8, 'e8':9, 'f8':10, 'g8':11, 'a8':12, 'b8':13}

In [6]:
len(note_seq), range(len(note_seq)-4) # [4,8,12,...]

(54, range(0, 50))

In [9]:
dataset = list()
for i in range(len(note_seq)-4):
  subset = note_seq[i:i+4]
  items = list()
  # print(subset)
  for item in subset:
    # print(code2idx[item]) # item = key, value 값이 나옴
    items.append(code2idx[item])
  # print(items)
  dataset.append(items)

print(dataset)

[[11, 9, 2, 10], [9, 2, 10, 8], [2, 10, 8, 1], [10, 8, 1, 7], [8, 1, 7, 8], [1, 7, 8, 9], [7, 8, 9, 10], [8, 9, 10, 11], [9, 10, 11, 11], [10, 11, 11, 4], [11, 11, 4, 11], [11, 4, 11, 9], [4, 11, 9, 9], [11, 9, 9, 9], [9, 9, 9, 10], [9, 9, 10, 8], [9, 10, 8, 1], [10, 8, 1, 7], [8, 1, 7, 9], [1, 7, 9, 11], [7, 9, 11, 11], [9, 11, 11, 9], [11, 11, 9, 9], [11, 9, 9, 2], [9, 9, 2, 8], [9, 2, 8, 8], [2, 8, 8, 8], [8, 8, 8, 8], [8, 8, 8, 8], [8, 8, 8, 9], [8, 8, 9, 3], [8, 9, 3, 9], [9, 3, 9, 9], [3, 9, 9, 9], [9, 9, 9, 9], [9, 9, 9, 9], [9, 9, 9, 10], [9, 9, 10, 4], [9, 10, 4, 11], [10, 4, 11, 9], [4, 11, 9, 2], [11, 9, 2, 10], [9, 2, 10, 8], [2, 10, 8, 1], [10, 8, 1, 7], [8, 1, 7, 9], [1, 7, 9, 11], [7, 9, 11, 11], [9, 11, 11, 9], [11, 11, 9, 9]]


In [10]:
import numpy as np
datasets = np.array(dataset)

In [16]:
x_train = datasets[:, 0:3]
x_train.shape # --> tensorflow tensor type(tensor) (50, 3, 1)

(50, 3)

In [21]:
X_train = np.reshape(x_train, (50, 3, 1))
X_train.shape, X_train[2]

((50, 3, 1), array([[0.01183432],
        [0.0591716 ],
        [0.04733728]]))

In [15]:
y_train = datasets[:,3]
y_train.shape

(50,)

In [17]:
len(code2idx)

14

In [19]:
x_train = x_train / 13
x_train[3]

array([0.0591716 , 0.04733728, 0.00591716])

In [22]:
np.unique(y_train)

array([ 1,  2,  3,  4,  7,  8,  9, 10, 11])

# make model

In [20]:
import tensorflow as tf

In [35]:
model = tf.keras.models.Sequential()

model.add(tf.keras.Input(shape=(3,1)))  # input layer
model.add(tf.keras.layers.LSTM(128)) # hidden layer
model.add(tf.keras.layers.Dense(13, activation='softmax')) # output layer

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy']) # gadget

In [51]:
hist = model.fit(X_train, y_train, epochs=500, batch_size=10)  # 50 / 5 = 10

Epoch 1/500
5/5 [==============================] - 0s 5ms/step - loss: 1.8257 - accuracy: 0.3400
Epoch 2/500
5/5 [==============================] - 0s 5ms/step - loss: 1.8270 - accuracy: 0.3400
Epoch 3/500
5/5 [==============================] - 0s 5ms/step - loss: 1.8214 - accuracy: 0.3400
Epoch 4/500
5/5 [==============================] - 0s 5ms/step - loss: 1.8200 - accuracy: 0.3400
Epoch 5/500
5/5 [==============================] - 0s 5ms/step - loss: 1.8194 - accuracy: 0.3400
Epoch 6/500
5/5 [==============================] - 0s 5ms/step - loss: 1.8208 - accuracy: 0.3400
Epoch 7/500
5/5 [==============================] - 0s 5ms/step - loss: 1.8193 - accuracy: 0.3400
Epoch 8/500
5/5 [==============================] - 0s 5ms/step - loss: 1.8198 - accuracy: 0.3400
Epoch 9/500
5/5 [==============================] - 0s 5ms/step - loss: 1.8142 - accuracy: 0.3400
Epoch 10/500
5/5 [==============================] - 0s 5ms/step - loss: 1.8138 - accuracy: 0.3400
Epoch 11/500
5/5 [===========

In [39]:
model.evaluate(X_train, y_train)

2/2 [==============================] - 0s 7ms/step - loss: 1.9258 - accuracy: 0.3400


[1.9257965087890625, 0.3400000035762787]

In [41]:
X_train[4:5]

array([[[0.04733728],
        [0.00591716],
        [0.04142012]]])

In [42]:
model.predict(X_train[4:5])

array([[0.01117667, 0.05753594, 0.02594022, 0.02560124, 0.04001329,
        0.01130049, 0.01275296, 0.06112053, 0.16438071, 0.34505776,
        0.09525719, 0.1375045 , 0.0123585 ]], dtype=float32)

In [45]:
first = 0.04733728
second = 0.00591716
third = 0.04142012

In [48]:
pred = model.predict([[[first],[second],[third]]])

In [49]:
np.argmax(pred)

9