# Sigmoid

In [1]:
import tensorflow as tf

In [6]:
a = tf.constant([4.0, 1.0, 3.0], dtype = tf.float32)
a, type(a)

(<tf.Tensor: shape=(3,), dtype=float32, numpy=array([4., 1., 3.], dtype=float32)>,
 tensorflow.python.framework.ops.EagerTensor)

In [7]:
b = tf.keras.activations.sigmoid(a)
b

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.98201376, 0.7310586 , 0.95257413], dtype=float32)>

In [8]:
b. numpy()

array([0.98201376, 0.7310586 , 0.95257413], dtype=float32)

#Softmax

In [12]:
inputs = tf.random.normal(shape=(1,3))

In [15]:
outputs = tf.keras.activations.softmax(inputs)
outputs

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0.6255638 , 0.12079572, 0.2536404 ]], dtype=float32)>

In [17]:
outputs.numpy()

array([[0.6255638 , 0.12079572, 0.2536404 ]], dtype=float32)